// @routes-hash e5f6abf4ece14ae283ef633f7f074684
import { Express } from "express";

import route1 from "./routes/admin/ai-config/getOverview";
import route2 from "./routes/admin/ai-config/updateDeployment";
import route3 from "./routes/admin/ai-config/updateUseMode";
import route4 from "./routes/admin/audit/listAudit";
import route5 from "./routes/admin/auth/session";
import route6 from "./routes/admin/concurrency/getPolicies";
import route7 from "./routes/admin/concurrency/updateGroupPolicy";
import route8 from "./routes/admin/concurrency/updateUserPolicy";
import route9 from "./routes/admin/groups/createGroup";
import route10 from "./routes/admin/groups/listGroups";
import route11 from "./routes/admin/groups/updateGroup";
import route12 from "./routes/admin/projects/listProjects";
import route13 from "./routes/admin/providers/getOverview";
import route14 from "./routes/admin/providers/getPricing";
import route15 from "./routes/admin/providers/testConnection";
import route16 from "./routes/admin/providers/updatePricing";
import route17 from "./routes/admin/providers/updateProvider";
import route18 from "./routes/admin/queue/cancelJob";
import route19 from "./routes/admin/queue/listJobs";
import route20 from "./routes/admin/queue/reprioritizeJob";
import route21 from "./routes/admin/quota/adjustQuota";
import route22 from "./routes/admin/quota/getOverview";
import route23 from "./routes/admin/system/getOverview";
import route24 from "./routes/admin/system/updateDevelopment";
import route25 from "./routes/admin/system/updateSupportContact";
import route26 from "./routes/admin/tasks/listTasks";
import route27 from "./routes/admin/usage/getOverview";
import route28 from "./routes/admin/users/createUser";
import route29 from "./routes/admin/users/listUsers";
import route30 from "./routes/admin/users/resetPassword";
import route31 from "./routes/admin/users/updateUser";
import route32 from "./routes/agents/clearMemory";
import route33 from "./routes/agents/getMemory";
import route34 from "./routes/artStyle/addArtStyle";
import route35 from "./routes/artStyle/editArtStyle";
import route36 from "./routes/artStyle/extractStylePrompt";
import route37 from "./routes/artStyle/getArtStyle";
import route38 from "./routes/assets/addAssets";
import route39 from "./routes/assets/addAudioAssets";
import route40 from "./routes/assets/batchDelete";
import route41 from "./routes/assets/batchGenerationData";
import route42 from "./routes/assets/delAssets";
import route43 from "./routes/assets/delImage";
import route44 from "./routes/assets/getAssetsApi";
import route45 from "./routes/assets/getImage";
import route46 from "./routes/assets/getMaterialData";
import route47 from "./routes/assets/pollingImageAssets";
import route48 from "./routes/assets/pollingPromptAssets";
import route49 from "./routes/assets/saveAssets";
import route50 from "./routes/assets/updateAssets";
import route51 from "./routes/assets/updateAudioAssets";
import route52 from "./routes/assets/uploadClip";
import route53 from "./routes/assetsGenerate/batchGenerateImageAssets";
import route54 from "./routes/assetsGenerate/batchPolishAssetsPrompt";
import route55 from "./routes/assetsGenerate/cancelGenerate";
import route56 from "./routes/assetsGenerate/generateAssets";
import route57 from "./routes/assetsGenerate/polishAssetsPrompt";
import route58 from "./routes/common/getBigImage";
import route59 from "./routes/cornerScape/batchBindAudio";
import route60 from "./routes/cornerScape/getAllAssets";
import route61 from "./routes/cornerScape/pollingAudio";
import route62 from "./routes/cornerScape/updateAssetsAudio";
import route63 from "./routes/general/generalStatistics";
import route64 from "./routes/general/getSingleProject";
import route65 from "./routes/general/updateProject";
import route66 from "./routes/generation/getJob";
import route67 from "./routes/generation/getPricingEstimate";
import route68 from "./routes/login/login";
import route69 from "./routes/modelSelect/getModelDetail";
import route70 from "./routes/modelSelect/getModelList";
import route71 from "./routes/novel/addNovel";
import route72 from "./routes/novel/batchDeleteNovel";
import route73 from "./routes/novel/delNovel";
import route74 from "./routes/novel/event/batchDeleteEvent";
import route75 from "./routes/novel/event/deletEvent";
import route76 from "./routes/novel/event/generateEvents";
import route77 from "./routes/novel/event/getEvent";
import route78 from "./routes/novel/getNovel";
import route79 from "./routes/novel/getNovelData";
import route80 from "./routes/novel/getNovelEventState";
import route81 from "./routes/novel/getNovelIndex";
import route82 from "./routes/novel/updateNovel";
import route83 from "./routes/other/deleteAllData";
import route84 from "./routes/other/getVersion";
import route85 from "./routes/production/assets/batchGenerateAssetsImage";
import route86 from "./routes/production/assets/deleteAssetsDireve";
import route87 from "./routes/production/assets/pollingImage";
import route88 from "./routes/production/assets/updateAssetsUrl";
import route89 from "./routes/production/editImage/generateFlowImage";
import route90 from "./routes/production/editImage/getImageDefaultModle";
import route91 from "./routes/production/editImage/getImageFlow";
import route92 from "./routes/production/editImage/saveImageFlow";
import route93 from "./routes/production/editImage/updateImageFlow";
import route94 from "./routes/production/editImage/uploadImage";
import route95 from "./routes/production/getFlowData";
import route96 from "./routes/production/getStoryboardData";
import route97 from "./routes/production/saveFlowData";
import route98 from "./routes/production/storyboard/addStoryboard";
import route99 from "./routes/production/storyboard/batchAddStoryboardInfo";
import route100 from "./routes/production/storyboard/batchDelete";
import route101 from "./routes/production/storyboard/batchGenerateImage";
import route102 from "./routes/production/storyboard/downPreviewImage";
import route103 from "./routes/production/storyboard/editStoryboardInfo";
import route104 from "./routes/production/storyboard/getStoryboardData";
import route105 from "./routes/production/storyboard/pollingImage";
import route106 from "./routes/production/storyboard/previewImage";
import route107 from "./routes/production/storyboard/removeFrame";
import route108 from "./routes/production/storyboard/updateStoryboardUrl";
import route109 from "./routes/production/workbench/addTrack";
import route110 from "./routes/production/workbench/batchGeneratePrompt";
import route111 from "./routes/production/workbench/batchGenerateVideo";
import route112 from "./routes/production/workbench/checkVideoPrompt";
import route113 from "./routes/production/workbench/checkVideoStateList";
import route114 from "./routes/production/workbench/deleteTrack";
import route115 from "./routes/production/workbench/delVideo";
import route116 from "./routes/production/workbench/generateVideo";
import route117 from "./routes/production/workbench/generateVideoPrompt";
import route118 from "./routes/production/workbench/getAudioBindAssetsList";
import route119 from "./routes/production/workbench/getFileUrl";
import route120 from "./routes/production/workbench/getGenerateData";
import route121 from "./routes/production/workbench/getVideoList";
import route122 from "./routes/production/workbench/selectVideo";
import route123 from "./routes/production/workbench/updateVideoDuration";
import route124 from "./routes/production/workbench/updateVideoPrompt";
import route125 from "./routes/project/addDirectorManual";
import route126 from "./routes/project/addProject";
import route127 from "./routes/project/addVisualManual";
import route128 from "./routes/project/deleteDirectorManual";
import route129 from "./routes/project/deleteVisualManual";
import route130 from "./routes/project/delProject";
import route131 from "./routes/project/editDirectorlManual";
import route132 from "./routes/project/editProject";
import route133 from "./routes/project/editVisualManual";
import route134 from "./routes/project/getModelDetails";
import route135 from "./routes/project/getProject";
import route136 from "./routes/project/getVisualManual";
import route137 from "./routes/project/queryDirectorManual";
import route138 from "./routes/project/visualManual";
import route139 from "./routes/public/support/getContact";
import route140 from "./routes/script/addScript";
import route141 from "./routes/script/batchAddScript";
import route142 from "./routes/script/delScript";
import route143 from "./routes/script/exportScript";
import route144 from "./routes/script/extractAssets";
import route145 from "./routes/script/getAiRegex";
import route146 from "./routes/script/getScrptApi";
import route147 from "./routes/script/pollScriptAssets";
import route148 from "./routes/script/updateScript";
import route149 from "./routes/scriptAgent/getPlanData";
import route150 from "./routes/scriptAgent/setPlanData";
import route151 from "./routes/scriptAgent/updateData";
import route152 from "./routes/setting/about/checkUpdate";
import route153 from "./routes/setting/about/downloadApp";
import route154 from "./routes/setting/agentDeploy/agentSetKey";
import route155 from "./routes/setting/agentDeploy/deployAgentModel";
import route156 from "./routes/setting/agentDeploy/getAgentDeploy";
import route157 from "./routes/setting/agentDeploy/getAgentUseMode";
import route158 from "./routes/setting/agentDeploy/updateAgentModel";
import route159 from "./routes/setting/agentDeploy/updateUseMode";
import route160 from "./routes/setting/dbConfig/clearData";
import route161 from "./routes/setting/dbConfig/clearTable";
import route162 from "./routes/setting/dbConfig/dbInfo";
import route163 from "./routes/setting/dbConfig/exportData";
import route164 from "./routes/setting/dbConfig/importData";
import route165 from "./routes/setting/dev/getSwitchAiDevTool";
import route166 from "./routes/setting/dev/updateSwitchAiDevTool";
import route167 from "./routes/setting/fileManagement/openFolder";
import route168 from "./routes/setting/getTextModel";
import route169 from "./routes/setting/loginConfig/getUser";
import route170 from "./routes/setting/loginConfig/me";
import route171 from "./routes/setting/loginConfig/updateUserPwd";
import route172 from "./routes/setting/memoryConfig/delAllMemory";
import route173 from "./routes/setting/memoryConfig/getMemory";
import route174 from "./routes/setting/memoryConfig/sureMemory";
import route175 from "./routes/setting/modelMap/bindingPrompt";
import route176 from "./routes/setting/modelMap/deletePrompt";
import route177 from "./routes/setting/modelMap/getImageAndVideoModel";
import route178 from "./routes/setting/modelMap/getPromptList";
import route179 from "./routes/setting/modelMap/savePrompt";
import route180 from "./routes/setting/modelMap/updatePrompt";
import route181 from "./routes/setting/promptManage/getPrompt";
import route182 from "./routes/setting/promptManage/updatePrompt";
import route183 from "./routes/setting/skillManagement/getSkillContent";
import route184 from "./routes/setting/skillManagement/getSkillList";
import route185 from "./routes/setting/skillManagement/saveSkillContent";
import route186 from "./routes/setting/userManagement/createUser";
import route187 from "./routes/setting/userManagement/listUsers";
import route188 from "./routes/setting/userManagement/resetPassword";
import route189 from "./routes/setting/userManagement/updateUser";
import route190 from "./routes/setting/vendorConfig/addVendor";
import route191 from "./routes/setting/vendorConfig/addVendorModel";
import route192 from "./routes/setting/vendorConfig/deleteVendor";
import route193 from "./routes/setting/vendorConfig/delVendorModel";
import route194 from "./routes/setting/vendorConfig/enableVendor";
import route195 from "./routes/setting/vendorConfig/getCodeByLink";
import route196 from "./routes/setting/vendorConfig/getVendorList";
import route197 from "./routes/setting/vendorConfig/modelTest";
import route198 from "./routes/setting/vendorConfig/modelTest/imageTest";
import route199 from "./routes/setting/vendorConfig/modelTest/textTest";
import route200 from "./routes/setting/vendorConfig/modelTest/videoTest";
import route201 from "./routes/setting/vendorConfig/updateCode";
import route202 from "./routes/setting/vendorConfig/updateVendorInputs";
import route203 from "./routes/setting/vendorConfig/upVendorModel";
import route204 from "./routes/task/getProject";
import route205 from "./routes/task/getTaskApi";
import route206 from "./routes/task/getTaskCategories";
import route207 from "./routes/task/taskDetails";
import route208 from "./routes/test/test";

export default async (app: Express) => {
  app.use("/api/admin/ai-config/getOverview", route1);
  app.use("/api/admin/ai-config/updateDeployment", route2);
  app.use("/api/admin/ai-config/updateUseMode", route3);
  app.use("/api/admin/audit/listAudit", route4);
  app.use("/api/admin/auth/session", route5);
  app.use("/api/admin/concurrency/getPolicies", route6);
  app.use("/api/admin/concurrency/updateGroupPolicy", route7);
  app.use("/api/admin/concurrency/updateUserPolicy", route8);
  app.use("/api/admin/groups/createGroup", route9);
  app.use("/api/admin/groups/listGroups", route10);
  app.use("/api/admin/groups/updateGroup", route11);
  app.use("/api/admin/projects/listProjects", route12);
  app.use("/api/admin/providers/getOverview", route13);
  app.use("/api/admin/providers/getPricing", route14);
  app.use("/api/admin/providers/testConnection", route15);
  app.use("/api/admin/providers/updatePricing", route16);
  app.use("/api/admin/providers/updateProvider", route17);
  app.use("/api/admin/queue/cancelJob", route18);
  app.use("/api/admin/queue/listJobs", route19);
  app.use("/api/admin/queue/reprioritizeJob", route20);
  app.use("/api/admin/quota/adjustQuota", route21);
  app.use("/api/admin/quota/getOverview", route22);
  app.use("/api/admin/system/getOverview", route23);
  app.use("/api/admin/system/updateDevelopment", route24);
  app.use("/api/admin/system/updateSupportContact", route25);
  app.use("/api/admin/tasks/listTasks", route26);
  app.use("/api/admin/usage/getOverview", route27);
  app.use("/api/admin/users/createUser", route28);
  app.use("/api/admin/users/listUsers", route29);
  app.use("/api/admin/users/resetPassword", route30);
  app.use("/api/admin/users/updateUser", route31);
  app.use("/api/agents/clearMemory", route32);
  app.use("/api/agents/getMemory", route33);
  app.use("/api/artStyle/addArtStyle", route34);
  app.use("/api/artStyle/editArtStyle", route35);
  app.use("/api/artStyle/extractStylePrompt", route36);
  app.use("/api/artStyle/getArtStyle", route37);
  app.use("/api/assets/addAssets", route38);
  app.use("/api/assets/addAudioAssets", route39);
  app.use("/api/assets/batchDelete", route40);
  app.use("/api/assets/batchGenerationData", route41);
  app.use("/api/assets/delAssets", route42);
  app.use("/api/assets/delImage", route43);
  app.use("/api/assets/getAssetsApi", route44);
  app.use("/api/assets/getImage", route45);
  app.use("/api/assets/getMaterialData", route46);
  app.use("/api/assets/pollingImageAssets", route47);
  app.use("/api/assets/pollingPromptAssets", route48);
  app.use("/api/assets/saveAssets", route49);
  app.use("/api/assets/updateAssets", route50);
  app.use("/api/assets/updateAudioAssets", route51);
  app.use("/api/assets/uploadClip", route52);
  app.use("/api/assetsGenerate/batchGenerateImageAssets", route53);
  app.use("/api/assetsGenerate/batchPolishAssetsPrompt", route54);
  app.use("/api/assetsGenerate/cancelGenerate", route55);
  app.use("/api/assetsGenerate/generateAssets", route56);
  app.use("/api/assetsGenerate/polishAssetsPrompt", route57);
  app.use("/api/common/getBigImage", route58);
  app.use("/api/cornerScape/batchBindAudio", route59);
  app.use("/api/cornerScape/getAllAssets", route60);
  app.use("/api/cornerScape/pollingAudio", route61);
  app.use("/api/cornerScape/updateAssetsAudio", route62);
  app.use("/api/general/generalStatistics", route63);
  app.use("/api/general/getSingleProject", route64);
  app.use("/api/general/updateProject", route65);
  app.use("/api/generation/getJob", route66);
  app.use("/api/generation/getPricingEstimate", route67);
  app.use("/api/login/login", route68);
  app.use("/api/modelSelect/getModelDetail", route69);
  app.use("/api/modelSelect/getModelList", route70);
  app.use("/api/novel/addNovel", route71);
  app.use("/api/novel/batchDeleteNovel", route72);
  app.use("/api/novel/delNovel", route73);
  app.use("/api/novel/event/batchDeleteEvent", route74);
  app.use("/api/novel/event/deletEvent", route75);
  app.use("/api/novel/event/generateEvents", route76);
  app.use("/api/novel/event/getEvent", route77);
  app.use("/api/novel/getNovel", route78);
  app.use("/api/novel/getNovelData", route79);
  app.use("/api/novel/getNovelEventState", route80);
  app.use("/api/novel/getNovelIndex", route81);
  app.use("/api/novel/updateNovel", route82);
  app.use("/api/other/deleteAllData", route83);
  app.use("/api/other/getVersion", route84);
  app.use("/api/production/assets/batchGenerateAssetsImage", route85);
  app.use("/api/production/assets/deleteAssetsDireve", route86);
  app.use("/api/production/assets/pollingImage", route87);
  app.use("/api/production/assets/updateAssetsUrl", route88);
  app.use("/api/production/editImage/generateFlowImage", route89);
  app.use("/api/production/editImage/getImageDefaultModle", route90);
  app.use("/api/production/editImage/getImageFlow", route91);
  app.use("/api/production/editImage/saveImageFlow", route92);
  app.use("/api/production/editImage/updateImageFlow", route93);
  app.use("/api/production/editImage/uploadImage", route94);
  app.use("/api/production/getFlowData", route95);
  app.use("/api/production/getStoryboardData", route96);
  app.use("/api/production/saveFlowData", route97);
  app.use("/api/production/storyboard/addStoryboard", route98);
  app.use("/api/production/storyboard/batchAddStoryboardInfo", route99);
  app.use("/api/production/storyboard/batchDelete", route100);
  app.use("/api/production/storyboard/batchGenerateImage", route101);
  app.use("/api/production/storyboard/downPreviewImage", route102);
  app.use("/api/production/storyboard/editStoryboardInfo", route103);
  app.use("/api/production/storyboard/getStoryboardData", route104);
  app.use("/api/production/storyboard/pollingImage", route105);
  app.use("/api/production/storyboard/previewImage", route106);
  app.use("/api/production/storyboard/removeFrame", route107);
  app.use("/api/production/storyboard/updateStoryboardUrl", route108);
  app.use("/api/production/workbench/addTrack", route109);
  app.use("/api/production/workbench/batchGeneratePrompt", route110);
  app.use("/api/production/workbench/batchGenerateVideo", route111);
  app.use("/api/production/workbench/checkVideoPrompt", route112);
  app.use("/api/production/workbench/checkVideoStateList", route113);
  app.use("/api/production/workbench/deleteTrack", route114);
  app.use("/api/production/workbench/delVideo", route115);
  app.use("/api/production/workbench/generateVideo", route116);
  app.use("/api/production/workbench/generateVideoPrompt", route117);
  app.use("/api/production/workbench/getAudioBindAssetsList", route118);
  app.use("/api/production/workbench/getFileUrl", route119);
  app.use("/api/production/workbench/getGenerateData", route120);
  app.use("/api/production/workbench/getVideoList", route121);
  app.use("/api/production/workbench/selectVideo", route122);
  app.use("/api/production/workbench/updateVideoDuration", route123);
  app.use("/api/production/workbench/updateVideoPrompt", route124);
  app.use("/api/project/addDirectorManual", route125);
  app.use("/api/project/addProject", route126);
  app.use("/api/project/addVisualManual", route127);
  app.use("/api/project/deleteDirectorManual", route128);
  app.use("/api/project/deleteVisualManual", route129);
  app.use("/api/project/delProject", route130);
  app.use("/api/project/editDirectorlManual", route131);
  app.use("/api/project/editProject", route132);
  app.use("/api/project/editVisualManual", route133);
  app.use("/api/project/getModelDetails", route134);
  app.use("/api/project/getProject", route135);
  app.use("/api/project/getVisualManual", route136);
  app.use("/api/project/queryDirectorManual", route137);
  app.use("/api/project/visualManual", route138);
  app.use("/api/public/support/getContact", route139);
  app.use("/api/script/addScript", route140);
  app.use("/api/script/batchAddScript", route141);
  app.use("/api/script/delScript", route142);
  app.use("/api/script/exportScript", route143);
  app.use("/api/script/extractAssets", route144);
  app.use("/api/script/getAiRegex", route145);
  app.use("/api/script/getScrptApi", route146);
  app.use("/api/script/pollScriptAssets", route147);
  app.use("/api/script/updateScript", route148);
  app.use("/api/scriptAgent/getPlanData", route149);
  app.use("/api/scriptAgent/setPlanData", route150);
  app.use("/api/scriptAgent/updateData", route151);
  app.use("/api/setting/about/checkUpdate", route152);
  app.use("/api/setting/about/downloadApp", route153);
  app.use("/api/setting/agentDeploy/agentSetKey", route154);
  app.use("/api/setting/agentDeploy/deployAgentModel", route155);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route156);
  app.use("/api/setting/agentDeploy/getAgentUseMode", route157);
  app.use("/api/setting/agentDeploy/updateAgentModel", route158);
  app.use("/api/setting/agentDeploy/updateUseMode", route159);
  app.use("/api/setting/dbConfig/clearData", route160);
  app.use("/api/setting/dbConfig/clearTable", route161);
  app.use("/api/setting/dbConfig/dbInfo", route162);
  app.use("/api/setting/dbConfig/exportData", route163);
  app.use("/api/setting/dbConfig/importData", route164);
  app.use("/api/setting/dev/getSwitchAiDevTool", route165);
  app.use("/api/setting/dev/updateSwitchAiDevTool", route166);
  app.use("/api/setting/fileManagement/openFolder", route167);
  app.use("/api/setting/getTextModel", route168);
  app.use("/api/setting/loginConfig/getUser", route169);
  app.use("/api/setting/loginConfig/me", route170);
  app.use("/api/setting/loginConfig/updateUserPwd", route171);
  app.use("/api/setting/memoryConfig/delAllMemory", route172);
  app.use("/api/setting/memoryConfig/getMemory", route173);
  app.use("/api/setting/memoryConfig/sureMemory", route174);
  app.use("/api/setting/modelMap/bindingPrompt", route175);
  app.use("/api/setting/modelMap/deletePrompt", route176);
  app.use("/api/setting/modelMap/getImageAndVideoModel", route177);
  app.use("/api/setting/modelMap/getPromptList", route178);
  app.use("/api/setting/modelMap/savePrompt", route179);
  app.use("/api/setting/modelMap/updatePrompt", route180);
  app.use("/api/setting/promptManage/getPrompt", route181);
  app.use("/api/setting/promptManage/updatePrompt", route182);
  app.use("/api/setting/skillManagement/getSkillContent", route183);
  app.use("/api/setting/skillManagement/getSkillList", route184);
  app.use("/api/setting/skillManagement/saveSkillContent", route185);
  app.use("/api/setting/userManagement/createUser", route186);
  app.use("/api/setting/userManagement/listUsers", route187);
  app.use("/api/setting/userManagement/resetPassword", route188);
  app.use("/api/setting/userManagement/updateUser", route189);
  app.use("/api/setting/vendorConfig/addVendor", route190);
  app.use("/api/setting/vendorConfig/addVendorModel", route191);
  app.use("/api/setting/vendorConfig/deleteVendor", route192);
  app.use("/api/setting/vendorConfig/delVendorModel", route193);
  app.use("/api/setting/vendorConfig/enableVendor", route194);
  app.use("/api/setting/vendorConfig/getCodeByLink", route195);
  app.use("/api/setting/vendorConfig/getVendorList", route196);
  app.use("/api/setting/vendorConfig/modelTest", route197);
  app.use("/api/setting/vendorConfig/modelTest/imageTest", route198);
  app.use("/api/setting/vendorConfig/modelTest/textTest", route199);
  app.use("/api/setting/vendorConfig/modelTest/videoTest", route200);
  app.use("/api/setting/vendorConfig/updateCode", route201);
  app.use("/api/setting/vendorConfig/updateVendorInputs", route202);
  app.use("/api/setting/vendorConfig/upVendorModel", route203);
  app.use("/api/task/getProject", route204);
  app.use("/api/task/getTaskApi", route205);
  app.use("/api/task/getTaskCategories", route206);
  app.use("/api/task/taskDetails", route207);
  app.use("/api/test/test", route208);
}
